// Stubs for Godot packed array types not present in the NuGet GodotSharp package.
// The full types are generated by the Godot editor; these allow the project to compile.
using System.Collections;
using System.Collections.Generic;
using GodotVector2 = Godot.Vector2;
using GodotVector3 = Godot.Vector3;

namespace Godot
{
    public class PackedVector3Array : IEnumerable<Vector3>
    {
        private readonly List<Vector3> _data = new();
        public int Count => _data.Count;
        public Vector3 this[int i] { get => _data[i]; set => _data[i] = value; }
        public void Resize(int n) { while (_data.Count < n) _data.Add(Vector3.Zero); while (_data.Count > n) _data.RemoveAt(_data.Count - 1); }
        public void Add(Vector3 v) => _data.Add(v);
        public IEnumerator<Vector3> GetEnumerator() => _data.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => _data.GetEnumerator();
    }

    public class PackedVector2Array : IEnumerable<Vector2>
    {
        private readonly List<Vector2> _data = new();
        public int Count => _data.Count;
        public Vector2 this[int i] { get => _data[i]; set => _data[i] = value; }
        public void Resize(int n) { while (_data.Count < n) _data.Add(Vector2.Zero); while (_data.Count > n) _data.RemoveAt(_data.Count - 1); }
        public void Add(Vector2 v) => _data.Add(v);
        public IEnumerator<Vector2> GetEnumerator() => _data.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => _data.GetEnumerator();
    }

    public class PackedFloat32Array : IEnumerable<float>
    {
        private readonly List<float> _data = new();
        public int Count => _data.Count;
        public float this[int i] { get => _data[i]; set => _data[i] = value; }
        public void Resize(int n) { while (_data.Count < n) _data.Add(0f); while (_data.Count > n) _data.RemoveAt(_data.Count - 1); }
        public void Add(float v) => _data.Add(v);
        public IEnumerator<float> GetEnumerator() => _data.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => _data.GetEnumerator();
    }

    public class PackedInt32Array : IEnumerable<int>
    {
        private readonly List<int> _data = new();
        public int Count => _data.Count;
        public int this[int i] { get => _data[i]; set => _data[i] = value; }
        public void Resize(int n) { while (_data.Count < n) _data.Add(0); while (_data.Count > n) _data.RemoveAt(_data.Count - 1); }
        public IEnumerator<int> GetEnumerator() => _data.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => _data.GetEnumerator();
    }
}
